### ISSUE TITLE
Screen: MouseWheel() removes active control...

### ISSUE THREAD

**Issue by KlonZK** [jk3064/chiliui#44]
..if the active control doesnt grab the wheel event - even when it has no use for it. consequently, the control either loses its claim on any further events that may happen down the line while the input is owned by the screen, or blocks the mousewheel.

in practice this means that while a mouse button is being pressed and owned by a control, the wheel cannot be used for anything else, most notably the camera.

the more sensible solution would be to treat the mousewheel seperately from claims on button events. if the active control returns a "false", Screen:MouseWheel() should simply return a "false" as well and leave the event for other widgets to handle.

**Comment by gajop** [comment]
Only the control that has a mouse button pressed should get mouse wheel events. This is how pretty much every other application works (e.g. you can't press buttons in your browser and simultaneously scroll the page).

What's your use case? The camera is not a good example (I can't imagine anyone doing that).

**Comment by KlonZK** [comment]
most controls never use wheel events tho, and spring is no normal application. i admit that currently there arent many cases where this would matter, but generally, controlling the camera with the wheel is something that should work when you arent hovering/focusing a control that uses wheel.

in my case i implemented a drag&drop system to move list items from one panel to another or from a panel into the world. while you are doing that, the mousewheel is "free", you dont really need it for the operation as such. if youre dragging into the world, being able to use the wheel to navigate would be useful.

**Comment by gajop** [comment]
I wrote a lengthy explanation why this isn't possible, and then wrote a fix in 3 lines: https://github.com/gajop/chiliui/commit/4dbaa2a4fa6d3b6871b7876cdd5ab25021cfed98

Part of an existing PR.
